#@host=https://<functionapp>.azurewebsites.net
@host=http://localhost:7071

### Create a new chat
PUT {{host}}/api/assistants/1


### Ask what time it is in a place to trigger GetTime function
POST  {{host}}/api/assistants/1
Content-Type: application/json

{
    "message": "What time is it in Tacoma?"
}


### Ask what the weather is in a place to trigger GetWeather function
POST  {{host}}/api/assistants/1
Content-Type: application/json

{
    "message": "What is the weather in Tacoma?"
}
